### ISSUE TITLE
Broken artisan optimize in Laravel 5.1

### ISSUE THREAD

**Issue by fgreinus** [antonioribeiro/firewall#61] opened 2017-02-13 10:41 UTC
Hey guys,

i was having problems with the php artisan optimize command building bad compiled.php file.

Error when using laravel with the compiled.php generated is:
`PHP Fatal error:  Cannot declare interface Illuminate\Contracts\Container\Container, because the name is already in use in /Users/fgreinus/Web/paladalo/bootstrap/cache/compiled.php on line 4`

Do you got any suggestions on how to fix this?

Additionally:
This also happens on a clean laravel 5.1 installation with only firewall installed.

**Comment by RobertBoes** [comment] 2017-03-03 08:17
The issue seems to be caused by support, see antonioribeiro/support#13

**Comment by antonioribeiro** [comment] 2017-08-19 20:04
Should be fixed in pragmarx/support 0.6.16.

**Closed by antonioribeiro** 2017-08-19 20:04 UTC
